name: 'Merger'
description: 'Merge source branch into target'
inputs:
  userName:
    description: 'git config user.name'
    default: 'Barry Mittens'
  userEmail:
    description: 'git config user.email'
    default: 'someone@test.com'
  source:
    description: 'Branch that needs to be merged'
    required: true
  target:
    description: 'The branch to merge into'
    required: true
  strategy:
    description: 'Merge strategy, defaults to theirs'
    default: 'theirs'
runs:
  using: "composite"
  steps:
    - name: Setup git
      shell: bash
      run: |
          git config --local user.email "${{ inputs.userEmail }}"
          git config --local user.name "${{ inputs.userName }}"
    - name: Merging process
      shell: bash
      run: |
          echo "Fetching all"
          git fetch --all
          echo "Doing checkout of branch ${{ inputs.target }}"
          git checkout ${{ inputs.target }}
          echo "Merging in ${{ inputs.source }} with the strategy being ${{ inputs.strategy }}"
          git merge --strategy-option=theirs ${{ inputs.source }}
          git commit --allow-empty -m "[skip ci]"
          echo "Pushing to origin"
          git push origin ${{ inputs.target }} -f